# installs required dependencies on the app server

- hosts: app
  remote_user: root
  tasks:
    - name: add Azul Zulu keys
      apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id=0x219BD9C9
    - name: attach Azul Zulu packages
      apt_repository: >
        repo='deb http://repos.azulsystems.com/ubuntu stable main'
        state=present
    - name: add Postgres keys
      apt_key: url='https://www.postgresql.org/media/keys/ACCC4CF8.asc'

    - name: attach Postgres source into APT
      apt_repository: >
        repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'

    - name: update a package registry
      apt: update_cache=yes
    - name: install dependencies
      apt: name={{ item }} state=latest install_recommends=yes
      with_items:
        - nginx
        - memcached
        - supervisor
        - 'zulu-8'
        - 'postgresql-9.5'
        - 'postgresql-client-9.5'
        - 'postgresql-server-dev-9.5'
        - 'python'
        - 'python-dev'
        - 'python-pip'

    - name: install psycopg2 for ansible
      pip: name=psycopg2

